# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/samples/container-app/src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/samples/api-cache/src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/samples/container-app/src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/samples/static-web-app/src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/samples/ai-chat-app/src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/samples/fastapi-webapp/src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/samples/function-storage/src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/samples/webapp-database/src"
    schedule:
      interval: "weekly"
